package com.leontsai.blesample

val GATTATTRIBUTES_DEVICE_NAME: String = ""//外设名称
val GATTATTRIBUTES_SERVICE_OPEN_DOOR: String = ""//Service的UUID
val GATTATTRIBUTES_CHARACTERISTIC_SEND_COMMAND: String = ""//发送命令特征值的UUID
val GATTATTRIBUTES_CHARACTERISTIC_RETURN_COMMAND: String = ""//返回命令特征值的UUID


